$From = "sender@example.com"
$To = "recipient1@example.com", "recipient2@example.com"
$Cc = "cc@example.com"
$Attachment = "C:\Temp\Attachment.jpg"
$Subject = "Example Subject"
$Body = "<h2>Example body heading</h2><br><br>"
$Body += "Example body text."
$SMTPServer = "smtp.example.com"
$SMTPPort = "587"
Send-MailMessage -From $From -to $To -Cc $Cc -Subject $Subject -Body $Body -BodyAsHtml -SmtpServer $SMTPServer -Port $SMTPPort -UseSsl -Credential (Get-Credential) -Attachments $Attachment
